import Head from "next/head";
import { AddContact } from "../../components/AddContact/AddContact";

const AddForm = () => {

  return (
    <div>
      <Head>
        <title>Gestion de contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AddContact />
    </div>
  );
};

export default AddForm;
