import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useContactsQuery } from "../api/contact";
import { ListContact } from "../components/ListContact/ListContact";

const Home: NextPage = () => {
  
  const { data:allContacts, isLoading, error } = useContactsQuery();

  return (
    <div className={styles.container}>
      <Head>
        <title>Gestion de contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ListContact contacts={allContacts!} />
    </div>
  );
};

export default Home;
